name: minosmobile
description: "App Minos"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Fz Poppins
      fonts:
        - asset: assets/fonts/FZ Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/FZ Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/FZ Poppins-Bold.ttf
          weight: 700





