name: minosmobile
description: "App Minos"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Fz Poppins
      fonts:
        - asset: assets/fonts/FZ Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/FZ Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/FZ Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/FZ Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/FZ Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/FZ Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FZ Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/FZ Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/FZ Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/FZ Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/FZ Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/FZ Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/FZ Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/FZ Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/FZ Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/FZ Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/FZ Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/FZ Poppins-BlackItalic.ttf
          weight: 900
          style: italic





